import mods.ntm.Anvil;
import mods.ntm.Assembler;

//HANDGUARDs
mods.ntm.Anvil.addRecipe(<mwc:dragunov98handguard>, [<hbm:wire_aluminium>, <hbm:plate_aluminium>], 3);
mods.ntm.Anvil.addRecipe(<mwc:ak74handguard>, [<hbm:wire_aluminium>, <hbm:plate_aluminium>], 3);
mods.ntm.Anvil.addRecipe(<mwc:ak101handguard>, [<hbm:wire_aluminium>, <hbm:plate_aluminium>], 3);
mods.ntm.Anvil.addRecipe(<mwc:mlokextendedhandguard>, [<hbm:wire_aluminium>, <hbm:plate_aluminium>], 3);
mods.ntm.Anvil.addRecipe(<mwc:mlokhandguard>, [<hbm:wire_aluminium>, <hbm:plate_aluminium>], 3);
mods.ntm.Anvil.addRecipe(<mwc:akmagpulhandleguardtan>, [<hbm:wire_aluminium>, <hbm:plate_aluminium>], 3);
mods.ntm.Anvil.addRecipe(<mwc:akmagpulhandleguard>, [<hbm:wire_aluminium>, <hbm:plate_aluminium>], 3);
mods.ntm.Anvil.addRecipe(<mwc:ak12handguard>, [<hbm:wire_aluminium>, <hbm:plate_aluminium>], 3);
mods.ntm.Anvil.addRecipe(<mwc:rpk16handguard>, [<hbm:wire_aluminium>, <hbm:plate_aluminium>], 3);
mods.ntm.Anvil.addRecipe(<mwc:ak12kalhandguard>, [<hbm:wire_aluminium>, <hbm:plate_aluminium>], 3);
mods.ntm.Anvil.addRecipe(<mwc:ak15handleguard>, [<hbm:wire_aluminium>, <hbm:plate_aluminium>], 3);
mods.ntm.Anvil.addRecipe(<mwc:ar10supersasshandguard>, [<hbm:wire_aluminium>, <hbm:plate_aluminium>], 3);
mods.ntm.Anvil.addRecipe(<mwc:z10handguard>, [<hbm:wire_aluminium>, <hbm:plate_aluminium>], 3);
mods.ntm.Anvil.addRecipe(<mwc:s710handguard>, [<hbm:wire_aluminium>, <hbm:plate_aluminium>], 3);
mods.ntm.Anvil.addRecipe(<mwc:mpxhandguardextended>, [<hbm:wire_aluminium>, <hbm:plate_aluminium>], 3);
mods.ntm.Anvil.addRecipe(<mwc:mpxhandguard>, [<hbm:wire_aluminium>, <hbm:plate_aluminium>], 3);
mods.ntm.Anvil.addRecipe(<mwc:sigmcxhandguardshort>, [<hbm:wire_aluminium>, <hbm:plate_aluminium>], 3);
mods.ntm.Anvil.addRecipe(<mwc:sigmcxhandguard>, [<hbm:wire_aluminium>, <hbm:plate_aluminium>], 3);
mods.ntm.Anvil.addRecipe(<mwc:dragunovhandguard>, [<hbm:wire_aluminium>, <hbm:plate_aluminium>], 3);
mods.ntm.Anvil.addRecipe(<mwc:ak47handleguard>, [<hbm:wire_aluminium>, <hbm:plate_aluminium>], 3);
mods.ntm.Anvil.addRecipe(<mwc:k2c1handguard>, [<hbm:wire_aluminium>, <hbm:plate_aluminium>], 3);
mods.ntm.Anvil.addRecipe(<mwc:mpxhandguardrailed>, [<hbm:wire_aluminium>, <hbm:plate_aluminium>], 3);
mods.ntm.Anvil.addRecipe(<mwc:fsstaclitehandguard>, [<hbm:wire_aluminium>, <hbm:plate_aluminium>], 3);
mods.ntm.Anvil.addRecipe(<mwc:m4magpulhandguard>, [<hbm:wire_aluminium>, <hbm:plate_aluminium>], 3);
mods.ntm.Anvil.addRecipe(<mwc:m4magpulhandguardtan>, [<hbm:wire_aluminium>, <hbm:plate_aluminium>], 3);
mods.ntm.Anvil.addRecipe(<mwc:m16handguard>, [<hbm:wire_aluminium>, <hbm:plate_aluminium>], 3);
mods.ntm.Anvil.addRecipe(<mwc:mk18handguard>, [<hbm:wire_aluminium>, <hbm:plate_aluminium>], 3);
mods.ntm.Anvil.addRecipe(<mwc:mk18handguardblack>, [<hbm:wire_aluminium>, <hbm:plate_aluminium>], 3);
mods.ntm.Anvil.addRecipe(<mwc:block2socomhandguard>, [<hbm:wire_aluminium>, <hbm:plate_aluminium>], 3); mods.ntm.Anvil.addRecipe(<mwc:m110handguard>, [<hbm:wire_aluminium>, <hbm:plate_aluminium>], 3);
mods.ntm.Anvil.addRecipe(<mwc:m16a4handguard>, [<hbm:wire_aluminium>, <hbm:plate_aluminium>], 3);
mods.ntm.Anvil.addRecipe(<mwc:m4carbinehandguard>, [<hbm:wire_aluminium>, <hbm:plate_aluminium>], 3);
mods.ntm.Anvil.addRecipe(<mwc:m16a1handguard>, [<hbm:wire_aluminium>, <hbm:plate_aluminium>], 3);
mods.ntm.Anvil.addRecipe(<mwc:ar15fn15handguard>, [<hbm:wire_aluminium>, <hbm:plate_aluminium>], 3);
mods.ntm.Anvil.addRecipe(<mwc:mp5sdhandguard>, [<hbm:wire_aluminium>, <hbm:plate_aluminium>], 3);
mods.ntm.Anvil.addRecipe(<mwc:lvoavhandguard>, [<hbm:wire_aluminium>, <hbm:plate_aluminium>], 3);
mods.ntm.Anvil.addRecipe(<mwc:mp5a5handguard>, [<hbm:wire_aluminium>, <hbm:plate_aluminium>], 3);
mods.ntm.Anvil.addRecipe(<mwc:scarmlokhandguard>, [<hbm:wire_aluminium>, <hbm:plate_aluminium>], 3);
mods.ntm.Anvil.addRecipe(<mwc:scarmidwestindustrieshandguard>, [<hbm:wire_aluminium>, <hbm:plate_aluminium>], 3);
mods.ntm.Anvil.addRecipe(<mwc:scarhhandguard>, [<hbm:wire_aluminium>, <hbm:plate_aluminium>], 3);
mods.ntm.Anvil.addRecipe(<mwc:scarhandguard>, [<hbm:wire_aluminium>, <hbm:plate_aluminium>], 3);
mods.ntm.Anvil.addRecipe(<mwc:g11handguardk2>, [<hbm:wire_aluminium>, <hbm:plate_aluminium>], 3);
mods.ntm.Anvil.addRecipe(<mwc:g11handguardk1>, [<hbm:wire_aluminium>, <hbm:plate_aluminium>], 3);
mods.ntm.Anvil.addRecipe(<mwc:hk417handguard>, [<hbm:wire_aluminium>, <hbm:plate_aluminium>], 3);
mods.ntm.Anvil.addRecipe(<mwc:hk416handguardblackandtan>, [<hbm:wire_aluminium>, <hbm:plate_aluminium>], 3);
mods.ntm.Anvil.addRecipe(<mwc:m38handguard>, [<hbm:wire_aluminium>, <hbm:plate_aluminium>], 3);
mods.ntm.Anvil.addRecipe(<mwc:vectormk1modularhandguard>, [<hbm:wire_aluminium>, <hbm:plate_aluminium>], 3);
mods.ntm.Anvil.addRecipe(<mwc:m4handguard>, [<hbm:wire_aluminium>, <hbm:plate_aluminium>], 3);
mods.ntm.Anvil.addRecipe(<mwc:sig556handguardka>, [<hbm:wire_aluminium>, <hbm:plate_aluminium>], 3);
mods.ntm.Anvil.addRecipe(<mwc:ar57handguard>, [<hbm:wire_aluminium>, <hbm:plate_aluminium>], 3);
mods.ntm.Anvil.addRecipe(<mwc:sig556handguardrailed>, [<hbm:wire_aluminium>, <hbm:plate_aluminium>], 3);
mods.ntm.Anvil.addRecipe(<mwc:ntw20guard>, [<hbm:wire_aluminium>, <hbm:plate_aluminium>], 3);
mods.ntm.Anvil.addRecipe(<mwc:sig556handguard>, [<hbm:wire_aluminium>, <hbm:plate_aluminium>], 3);
mods.ntm.Anvil.addRecipe(<mwc:hk417handguardtan>, [<hbm:wire_aluminium>, <hbm:plate_aluminium>], 3);
mods.ntm.Anvil.addRecipe(<mwc:dsr1handguard>, [<hbm:wire_aluminium>, <hbm:plate_aluminium>], 3);
mods.ntm.Anvil.addRecipe(<mwc:g3handguardrailed>, [<hbm:wire_aluminium>, <hbm:plate_aluminium>], 3);
mods.ntm.Anvil.addRecipe(<mwc:g3a1handguard>, [<hbm:wire_aluminium>, <hbm:plate_aluminium>], 3);
mods.ntm.Anvil.addRecipe(<mwc:m1scoutcarbinehandguard>, [<hbm:wire_aluminium>, <hbm:plate_aluminium>], 3);
mods.ntm.Anvil.addRecipe(<mwc:dsr1handguardrailed>, [<hbm:wire_aluminium>, <hbm:plate_aluminium>], 3);
mods.ntm.Anvil.addRecipe(<mwc:mp5bmhandguard>, [<hbm:wire_aluminium>, <hbm:plate_aluminium>], 3);
mods.ntm.Anvil.addRecipe(<mwc:utgtrirailhandguard>, [<hbm:wire_aluminium>, <hbm:plate_aluminium>], 3);
mods.ntm.Anvil.addRecipe(<mwc:mp5navyhandguard>, [<hbm:wire_aluminium>, <hbm:plate_aluminium>], 3);
mods.ntm.Anvil.addRecipe(<mwc:scorpionevo3a1handguardlong>, [<hbm:wire_aluminium>, <hbm:plate_aluminium>], 3);
mods.ntm.Anvil.addRecipe(<mwc:scorpionevo3a1handguardshort>, [<hbm:wire_aluminium>, <hbm:plate_aluminium>], 3);
mods.ntm.Anvil.addRecipe(<mwc:mimp5mhandguard>, [<hbm:wire_aluminium>, <hbm:plate_aluminium>], 3);
mods.ntm.Anvil.addRecipe(<mwc:m249upperhandguard>, [<hbm:wire_aluminium>, <hbm:plate_aluminium>], 3);
mods.ntm.Anvil.addRecipe(<mwc:mk48handguard>, [<hbm:wire_aluminium>, <hbm:plate_aluminium>], 3);
mods.ntm.Anvil.addRecipe(<mwc:m249handguard>, [<hbm:wire_aluminium>, <hbm:plate_aluminium>], 3);
mods.ntm.Anvil.addRecipe(<mwc:m60e4guard>, [<hbm:wire_aluminium>, <hbm:plate_aluminium>], 3);
mods.ntm.Anvil.addRecipe(<mwc:stonerhandguard>, [<hbm:wire_aluminium>, <hbm:plate_aluminium>], 3);
mods.ntm.Anvil.addRecipe(<mwc:mk48upperhandguard>, [<hbm:wire_aluminium>, <hbm:plate_aluminium>], 3);
mods.ntm.Anvil.addRecipe(<mwc:auga2handguard>, [<hbm:wire_aluminium>, <hbm:plate_aluminium>], 3);
mods.ntm.Anvil.addRecipe(<mwc:m1carbineventilatedhandguard>, [<hbm:wire_aluminium>, <hbm:plate_aluminium>], 3);
mods.ntm.Anvil.addRecipe(<mwc:ef88handguard>, [<hbm:wire_aluminium>, <hbm:plate_aluminium>], 3);
mods.ntm.Anvil.addRecipe(<mwc:m1carbinehandguard>, [<hbm:wire_aluminium>, <hbm:plate_aluminium>], 3);
mods.ntm.Anvil.addRecipe(<mwc:auga3handguard>, [<hbm:wire_aluminium>, <hbm:plate_aluminium>], 3);
mods.ntm.Anvil.addRecipe(<mwc:acrprecisionhandguardtan>, [<hbm:wire_aluminium>, <hbm:plate_aluminium>], 3);
mods.ntm.Anvil.addRecipe(<mwc:acrwemskhandguardtan>, [<hbm:wire_aluminium>, <hbm:plate_aluminium>], 3);
mods.ntm.Anvil.addRecipe(<mwc:acrhandguardblack>, [<hbm:wire_aluminium>, <hbm:plate_aluminium>], 3);
mods.ntm.Anvil.addRecipe(<mwc:acrhandguard>, [<hbm:wire_aluminium>, <hbm:plate_aluminium>], 3);
mods.ntm.Anvil.addRecipe(<mwc:acrsquaredrophandguardtan>, [<hbm:wire_aluminium>, <hbm:plate_aluminium>], 3);
mods.ntm.Anvil.addRecipe(<mwc:acrpolymerhandguardtan>, [<hbm:wire_aluminium>, <hbm:plate_aluminium>], 3);
mods.ntm.Anvil.addRecipe(<mwc:acrsbrhandguardtan>, [<hbm:wire_aluminium>, <hbm:plate_aluminium>], 3);
mods.ntm.Anvil.addRecipe(<mwc:m60handguard>, [<hbm:wire_aluminium>, <hbm:plate_aluminium>], 3);
mods.ntm.Anvil.addRecipe(<mwc:honeybadgermatrixarmshandguard>, [<hbm:wire_aluminium>, <hbm:plate_aluminium>], 3);
mods.ntm.Anvil.addRecipe(<mwc:honeybadgerhandguard>, [<hbm:wire_aluminium>, <hbm:plate_aluminium>], 3);
mods.ntm.Anvil.addRecipe(<mwc:type20handguard>, [<hbm:wire_aluminium>, <hbm:plate_aluminium>], 3);
mods.ntm.Anvil.addRecipe(<mwc:kbp9a91kulatachandguard>, [<hbm:wire_aluminium>, <hbm:plate_aluminium>], 3);
mods.ntm.Anvil.addRecipe(<mwc:kbp9a91handguard>, [<hbm:wire_aluminium>, <hbm:plate_aluminium>], 3);
mods.ntm.Anvil.addRecipe(<mwc:ak12bhandguard>, [<hbm:wire_aluminium>, <hbm:plate_aluminium>], 3);
mods.ntm.Anvil.addRecipe(<mwc:fnfalhandguard>, [<hbm:wire_aluminium>, <hbm:plate_aluminium>], 3);
mods.ntm.Anvil.addRecipe(<mwc:asvalhandguard>, [<hbm:wire_aluminium>, <hbm:plate_aluminium>], 3);
mods.ntm.Anvil.addRecipe(<mwc:vssvintorezhandguard>, [<hbm:wire_aluminium>, <hbm:plate_aluminium>], 3);
mods.ntm.Anvil.addRecipe(<mwc:kbp9a91compacthandguard>, [<hbm:wire_aluminium>, <hbm:plate_aluminium>], 3);
mods.ntm.Anvil.addRecipe(<mwc:hks20handguard>, [<hbm:wire_aluminium>, <hbm:plate_aluminium>], 3);
mods.ntm.Anvil.addRecipe(<mwc:origin12handguard>, [<hbm:wire_aluminium>, <hbm:plate_aluminium>], 3);
mods.ntm.Anvil.addRecipe(<mwc:vectorcarbinehandguard>, [<hbm:wire_aluminium>, <hbm:plate_aluminium>], 3);
mods.ntm.Anvil.addRecipe(<mwc:fnfalparahandguard>, [<hbm:wire_aluminium>, <hbm:plate_aluminium>], 3);
//MOUNTs
mods.ntm.Anvil.addRecipe(<mwc:vssvintoreztrirailmount>, <hbm:plate_aluminium>, 3);
mods.ntm.Anvil.addRecipe(<mwc:samuraiedgemount>, <hbm:plate_aluminium>, 3);
mods.ntm.Anvil.addRecipe(<mwc:famasf1scopemount>, <hbm:plate_aluminium>, 3);
mods.ntm.Anvil.addRecipe(<mwc:m16a1scopemount>, <hbm:plate_aluminium>, 3);
mods.ntm.Anvil.addRecipe(<mwc:m14rail>, <hbm:plate_aluminium>, 3);
mods.ntm.Anvil.addRecipe(<mwc:mas21mount>, <hbm:plate_aluminium>, 3);
mods.ntm.Anvil.addRecipe(<mwc:fabdefensemount>, <hbm:plate_aluminium>, 3);
mods.ntm.Anvil.addRecipe(<mwc:vssvintoreztrirailmount>, <hbm:plate_aluminium>, 3);
mods.ntm.Anvil.addRecipe(<mwc:samuraiedgemount>, <hbm:plate_aluminium>, 3);
mods.ntm.Anvil.addRecipe(<mwc:famasf1scopemount>, <hbm:plate_aluminium>, 3);
mods.ntm.Anvil.addRecipe(<mwc:m16a1scopemount>, <hbm:plate_aluminium>, 3);
mods.ntm.Anvil.addRecipe(<mwc:m14rail>, <hbm:plate_aluminium>, 3);
mods.ntm.Anvil.addRecipe(<mwc:mas21mount>, <hbm:plate_aluminium>, 3);
//RECIVERs
mods.ntm.Anvil.addRecipe(<mwc:ump45receiver>, <hbm:ingot_aluminium>, 3);
mods.ntm.Anvil.addRecipe(<mwc:ump9receiver>, <hbm:ingot_aluminium>, 3);
mods.ntm.Anvil.addRecipe(<mwc:m4receiver>, <hbm:ingot_aluminium>, 3);
mods.ntm.Anvil.addRecipe(<mwc:beowulf50calreceiver>, <hbm:ingot_aluminium>, 3);
mods.ntm.Anvil.addRecipe(<mwc:m110receiver>, <hbm:ingot_aluminium>, 3);
mods.ntm.Anvil.addRecipe(<mwc:hk417receivertan>, <hbm:ingot_aluminium>, 3);
mods.ntm.Anvil.addRecipe(<mwc:ar57receiver>, <hbm:ingot_aluminium>, 3);
mods.ntm.Anvil.addRecipe(<mwc:vltorreceiver>, <hbm:ingot_aluminium>, 3);
mods.ntm.Anvil.addRecipe(<mwc:c8sfwreceiver>, <hbm:ingot_aluminium>, 3);
mods.ntm.Anvil.addRecipe(<mwc:s710receiver>, <hbm:ingot_aluminium>, 3);
mods.ntm.Anvil.addRecipe(<mwc:honeybadgerknightsreceiverblack>, <hbm:ingot_aluminium>, 3);
mods.ntm.Anvil.addRecipe(<mwc:hk417receiver>, <hbm:ingot_aluminium>, 3);
mods.ntm.Anvil.addRecipe(<mwc:z10receiver>, <hbm:ingot_aluminium>, 3);
mods.ntm.Anvil.addRecipe(<mwc:honeybadgerknightsreceiver>, <hbm:ingot_aluminium>, 3);
mods.ntm.Anvil.addRecipe(<mwc:honeybadgerreceiverblack>, <hbm:ingot_aluminium>, 3);
mods.ntm.Anvil.addRecipe(<mwc:honeybadgerreceiver>, <hbm:ingot_aluminium>, 3);
mods.ntm.Anvil.addRecipe(<mwc:cz805brenreceiver>, <hbm:ingot_aluminium>, 3);
mods.ntm.Anvil.addRecipe(<mwc:hk416receiver>, <hbm:ingot_aluminium>, 3);
mods.ntm.Anvil.addRecipe(<mwc:scarlreceiver>, <hbm:ingot_aluminium>, 3);
mods.ntm.Anvil.addRecipe(<mwc:krissvectorreceiver>, <hbm:ingot_aluminium>, 3);
//GRIPs
mods.ntm.Anvil.addRecipe(<mwc:origin12grip>, <hbm:ingot_aluminium>, 3);
mods.ntm.Anvil.addRecipe(<mwc:hks20grip>, <hbm:ingot_aluminium>, 3);
mods.ntm.Anvil.addRecipe(<mwc:m1014grip>, <hbm:ingot_aluminium>, 3);
mods.ntm.Anvil.addRecipe(<mwc:sccycpx2griptape>, <hbm:ingot_aluminium>, 3);
mods.ntm.Anvil.addRecipe(<mwc:mp5hoguegrip>, <hbm:ingot_aluminium>, 3);
mods.ntm.Anvil.addRecipe(<mwc:glockhoguegrip>, <hbm:ingot_aluminium>, 3);
mods.ntm.Anvil.addRecipe(<mwc:apsgrip>, <hbm:ingot_aluminium>, 3);
mods.ntm.Anvil.addRecipe(<mwc:mac10grip>, <hbm:ingot_aluminium>, 3);
mods.ntm.Anvil.addRecipe(<mwc:apsgrip>, <hbm:ingot_aluminium>, 3);
mods.ntm.Anvil.addRecipe(<mwc:junogrip>, <hbm:ingot_aluminium>, 3);
mods.ntm.Anvil.addRecipe(<mwc:m1a1grip>, <hbm:ingot_aluminium>, 3);
mods.ntm.Anvil.addRecipe(<mwc:m1928grip>, <hbm:ingot_aluminium>, 3);
mods.ntm.Anvil.addRecipe(<mwc:ks23raptorgrip>, <hbm:ingot_aluminium>, 3);
mods.ntm.Anvil.addRecipe(<mwc:fnfalgrip>, <hbm:ingot_aluminium>, 3);
mods.ntm.Anvil.addRecipe(<mwc:remington870sawedgrip>, <hbm:ingot_aluminium>, 3);
mods.ntm.Anvil.addRecipe(<mwc:gripplaceholder>, <hbm:ingot_aluminium>, 3);
mods.ntm.Anvil.addRecipe(<mwc:ak12grip>, <hbm:ingot_aluminium>, 3);
mods.ntm.Anvil.addRecipe(<mwc:m40a6gripplaceholder>, <hbm:ingot_aluminium>, 3);
mods.ntm.Anvil.addRecipe(<mwc:akergogriptan>, <hbm:ingot_aluminium>, 3);
mods.ntm.Anvil.addRecipe(<mwc:heraarmsgrip>, <hbm:ingot_aluminium>, 3);
mods.ntm.Anvil.addRecipe(<mwc:m4grip>, <hbm:ingot_aluminium>, 3);
mods.ntm.Anvil.addRecipe(<mwc:m4griptan>, <hbm:ingot_aluminium>, 3);
mods.ntm.Anvil.addRecipe(<mwc:m4gripgray>, <hbm:ingot_aluminium>, 3);
mods.ntm.Anvil.addRecipe(<mwc:hk416grip>, <hbm:ingot_aluminium>, 3);
mods.ntm.Anvil.addRecipe(<mwc:hk416griptan>, <hbm:ingot_aluminium>, 3);
mods.ntm.Anvil.addRecipe(<mwc:m110grip>, <hbm:ingot_aluminium>, 3);
mods.ntm.Anvil.addRecipe(<mwc:s710tricungrip>, <hbm:ingot_aluminium>, 3);
mods.ntm.Anvil.addRecipe(<mwc:k2c1grip>, <hbm:ingot_aluminium>, 3);
mods.ntm.Anvil.addRecipe(<mwc:ak47grip>, <hbm:ingot_aluminium>, 3);
mods.ntm.Anvil.addRecipe(<mwc:ak101grip>, <hbm:ingot_aluminium>, 3);
mods.ntm.Anvil.addRecipe(<mwc:akergogrip>, <hbm:ingot_aluminium>, 3);
mods.ntm.Anvil.addRecipe(<mwc:akergogripgreen>, <hbm:ingot_aluminium>, 3);
mods.ntm.Anvil.addRecipe(<mwc:glockhoguegriptan>, <hbm:ingot_aluminium>, 3);
mods.ntm.Anvil.addRecipe(<mwc:sig556grip>, <hbm:ingot_aluminium>, 3);
mods.ntm.Anvil.addRecipe(<mwc:vectortapedgrip>, <hbm:ingot_aluminium>, 3);
mods.ntm.Anvil.addRecipe(<mwc:g2contendergrip>, <hbm:ingot_aluminium>, 3);
mods.ntm.Anvil.addRecipe(<mwc:auggrip>, <hbm:ingot_aluminium>, 3);
mods.ntm.Anvil.addRecipe(<mwc:ak12ergogrip>, <hbm:ingot_aluminium>, 3);
//BARRELs
mods.ntm.Anvil.addRecipe(<mwc:m32barrel>, <hbm:plate_aluminium>, 3);
mods.ntm.Anvil.addRecipe(<mwc:remington870barrel>, <hbm:plate_aluminium>, 3);
mods.ntm.Anvil.addRecipe(<mwc:remington870policemagnumbarrel>, <hbm:plate_aluminium>, 3);
mods.ntm.Anvil.addRecipe(<mwc:remington870sawedbarrel>, <hbm:plate_aluminium>, 3);
mods.ntm.Anvil.addRecipe(<mwc:ks23barrel>, <hbm:plate_aluminium>, 3);
mods.ntm.Anvil.addRecipe(<mwc:ks23extendedbarrel>, <hbm:plate_aluminium>, 3);
mods.ntm.Anvil.addRecipe(<mwc:rpkbarrel>, <hbm:plate_aluminium>, 3);
mods.ntm.Anvil.addRecipe(<mwc:mas21barrel>, <hbm:plate_aluminium>, 3);
mods.ntm.Anvil.addRecipe(<mwc:m134barrels>, <hbm:plate_aluminium>, 3);
mods.ntm.Anvil.addRecipe(<mwc:ntw20barrel>, <hbm:plate_aluminium>, 3);
mods.ntm.Anvil.addRecipe(<mwc:hs12barrels>, <hbm:plate_aluminium>, 3);
mods.ntm.Anvil.addRecipe(<mwc:mp43edoublebarrel>, <hbm:plate_aluminium>, 3);
mods.ntm.Anvil.addRecipe(<mwc:g2contenderbarrelshort>, <hbm:plate_aluminium>, 3);
mods.ntm.Anvil.addRecipe(<mwc:g2contenderbarrellong>, <hbm:plate_aluminium>, 3);
mods.ntm.Anvil.addRecipe(<mwc:dsr1barrel>, <hbm:plate_aluminium>, 3);
mods.ntm.Anvil.addRecipe(<mwc:dsr1barrellong>, <hbm:plate_aluminium>, 3);
//STOCKs
mods.ntm.Anvil.addRecipe(<mwc:glock18cstock>, [<hbm:wire_aluminium>, <hbm:plate_aluminium>*2], 3);
mods.ntm.Anvil.addRecipe(<mwc:ump45stock>, [<hbm:wire_aluminium>, <hbm:plate_aluminium>*2], 3);
mods.ntm.Anvil.addRecipe(<mwc:vectorstockadapter>, [<hbm:wire_aluminium>, <hbm:plate_aluminium>*2], 3);
mods.ntm.Anvil.addRecipe(<mwc:scarhstock>, [<hbm:wire_aluminium>, <hbm:plate_aluminium>*2], 3);
mods.ntm.Anvil.addRecipe(<mwc:scaradapterstock>, [<hbm:wire_aluminium>, <hbm:plate_aluminium>*2], 3);
mods.ntm.Anvil.addRecipe(<mwc:scarretractablestock>, [<hbm:wire_aluminium>, <hbm:plate_aluminium>*2], 3);
mods.ntm.Anvil.addRecipe(<mwc:scarstock>, [<hbm:wire_aluminium>, <hbm:plate_aluminium>*2], 3);
mods.ntm.Anvil.addRecipe(<mwc:hks20stock>, [<hbm:wire_aluminium>, <hbm:plate_aluminium>*2], 3);
mods.ntm.Anvil.addRecipe(<mwc:origin12stock>, [<hbm:wire_aluminium>, <hbm:plate_aluminium>*2], 3);
mods.ntm.Anvil.addRecipe(<mwc:g2contenderstock>, [<hbm:wire_aluminium>, <hbm:plate_aluminium>*2], 3);
mods.ntm.Anvil.addRecipe(<mwc:g3stock>, [<hbm:wire_aluminium>, <hbm:plate_aluminium>*2], 3);
mods.ntm.Anvil.addRecipe(<mwc:mp5stockadapter>, [<hbm:wire_aluminium>, <hbm:plate_aluminium>*2], 3);
mods.ntm.Anvil.addRecipe(<mwc:honeybadgerstock>, [<hbm:wire_aluminium>, <hbm:plate_aluminium>*2], 3);
mods.ntm.Anvil.addRecipe(<mwc:honeybadgerstockblack>, [<hbm:wire_aluminium>, <hbm:plate_aluminium>*2], 3);
mods.ntm.Anvil.addRecipe(<mwc:mp7stock>, [<hbm:wire_aluminium>, <hbm:plate_aluminium>*2], 3);
mods.ntm.Anvil.addRecipe(<mwc:mp7milspecstock>, [<hbm:wire_aluminium>, <hbm:plate_aluminium>*2], 3);
mods.ntm.Anvil.addRecipe(<mwc:ak47stock>, [<hbm:wire_aluminium>, <hbm:plate_aluminium>*2], 3);
mods.ntm.Anvil.addRecipe(<mwc:dragunovgripstock>, [<hbm:wire_aluminium>, <hbm:plate_aluminium>*2], 3);
mods.ntm.Anvil.addRecipe(<mwc:dragunov98stock>, [<hbm:wire_aluminium>, <hbm:plate_aluminium>*2], 3);
mods.ntm.Anvil.addRecipe(<mwc:rpkstock>, [<hbm:wire_aluminium>, <hbm:plate_aluminium>*2], 3);
mods.ntm.Anvil.addRecipe(<mwc:m249milspecstock>, [<hbm:wire_aluminium>, <hbm:plate_aluminium>*2], 3);
mods.ntm.Anvil.addRecipe(<mwc:acrlongrangestock>, [<hbm:wire_aluminium>, <hbm:plate_aluminium>*2], 3);
mods.ntm.Anvil.addRecipe(<mwc:acrstockblack>, [<hbm:wire_aluminium>, <hbm:plate_aluminium>*2], 3);
mods.ntm.Anvil.addRecipe(<mwc:acrfixedstocktan>, [<hbm:wire_aluminium>, <hbm:plate_aluminium>*2], 3);
mods.ntm.Anvil.addRecipe(<mwc:acrprsstocktan>, [<hbm:wire_aluminium>, <hbm:plate_aluminium>*2], 3);
mods.ntm.Anvil.addRecipe(<mwc:acrpdwstock>, [<hbm:wire_aluminium>, <hbm:plate_aluminium>*2], 3);
mods.ntm.Anvil.addRecipe(<mwc:m1014stock>, [<hbm:wire_aluminium>, <hbm:plate_aluminium>*2], 3);
mods.ntm.Anvil.addRecipe(<mwc:m4benellistock>, [<hbm:wire_aluminium>, <hbm:plate_aluminium>*2], 3);
mods.ntm.Anvil.addRecipe(<mwc:spas12stock>, [<hbm:wire_aluminium>, <hbm:plate_aluminium>*2], 3);
mods.ntm.Anvil.addRecipe(<mwc:m249stock>, [<hbm:wire_aluminium>, <hbm:plate_aluminium>*2], 3);
mods.ntm.Anvil.addRecipe(<mwc:m249parastock>, [<hbm:wire_aluminium>, <hbm:plate_aluminium>*2], 3);
mods.ntm.Anvil.addRecipe(<mwc:m249hk416stock>, [<hbm:wire_aluminium>, <hbm:plate_aluminium>*2], 3);
mods.ntm.Anvil.addRecipe(<mwc:apsstock>, [<hbm:wire_aluminium>, <hbm:plate_aluminium>*2], 3);
mods.ntm.Anvil.addRecipe(<mwc:vectorstock>, [<hbm:wire_aluminium>, <hbm:plate_aluminium>*2], 3);
mods.ntm.Anvil.addRecipe(<mwc:acrstock>, [<hbm:wire_aluminium>, <hbm:plate_aluminium>*2], 3);
mods.ntm.Anvil.addRecipe(<mwc:mac21stock>, [<hbm:wire_aluminium>, <hbm:plate_aluminium>*2], 3);
mods.ntm.Anvil.addRecipe(<mwc:mac10stock>, [<hbm:wire_aluminium>, <hbm:plate_aluminium>*2], 3);
mods.ntm.Anvil.addRecipe(<mwc:vssvintorezmilspecstock>, [<hbm:wire_aluminium>, <hbm:plate_aluminium>*2], 3);
mods.ntm.Anvil.addRecipe(<mwc:asvalstock>, [<hbm:wire_aluminium>, <hbm:plate_aluminium>*2], 3);
mods.ntm.Anvil.addRecipe(<mwc:ak12zenitcostock>, [<hbm:wire_aluminium>, <hbm:plate_aluminium>*2], 3);
mods.ntm.Anvil.addRecipe(<mwc:ak12stock>, [<hbm:wire_aluminium>, <hbm:plate_aluminium>*2], 3);
mods.ntm.Anvil.addRecipe(<mwc:ak74stock>, [<hbm:wire_aluminium>, <hbm:plate_aluminium>*2], 3);
mods.ntm.Anvil.addRecipe(<mwc:ak101stock>, [<hbm:wire_aluminium>, <hbm:plate_aluminium>*2], 3);
mods.ntm.Anvil.addRecipe(<mwc:mp5stock>, [<hbm:wire_aluminium>, <hbm:plate_aluminium>*2], 3);
mods.ntm.Anvil.addRecipe(<mwc:mp5a3stock>, [<hbm:wire_aluminium>, <hbm:plate_aluminium>*2], 3);
mods.ntm.Anvil.addRecipe(<mwc:mp5a4stock>, [<hbm:wire_aluminium>, <hbm:plate_aluminium>*2], 3);
mods.ntm.Anvil.addRecipe(<mwc:m16stock>, [<hbm:wire_aluminium>, <hbm:plate_aluminium>*2], 3);
mods.ntm.Anvil.addRecipe(<mwc:vp70stock>, [<hbm:wire_aluminium>, <hbm:plate_aluminium>*2], 3);
mods.ntm.Anvil.addRecipe(<mwc:hk416stock>, [<hbm:wire_aluminium>, <hbm:plate_aluminium>*2], 3);
mods.ntm.Anvil.addRecipe(<mwc:socom_stock>, [<hbm:wire_aluminium>, <hbm:plate_aluminium>*2], 3);
mods.ntm.Anvil.addRecipe(<mwc:heraarmsstock>, [<hbm:wire_aluminium>, <hbm:plate_aluminium>*2], 3);
mods.ntm.Anvil.addRecipe(<mwc:ks23stock>, [<hbm:wire_aluminium>, <hbm:plate_aluminium>*2], 3);
mods.ntm.Anvil.addRecipe(<mwc:sigmcxstock>, [<hbm:wire_aluminium>, <hbm:plate_aluminium>*2], 3);
mods.ntm.Anvil.addRecipe(<mwc:milspecstocktan>, [<hbm:wire_aluminium>, <hbm:plate_aluminium>*2], 3);
mods.ntm.Anvil.addRecipe(<mwc:c8stock>, [<hbm:wire_aluminium>, <hbm:plate_aluminium>*2], 3);
mods.ntm.Anvil.addRecipe(<mwc:ks23mstock>, [<hbm:wire_aluminium>, <hbm:plate_aluminium>*2], 3);
mods.ntm.Anvil.addRecipe(<mwc:remington870hk416stockstock>, [<hbm:wire_aluminium>, <hbm:plate_aluminium>*2], 3);
mods.ntm.Anvil.addRecipe(<mwc:remington870milspecstock>, [<hbm:wire_aluminium>, <hbm:plate_aluminium>*2], 3);
mods.ntm.Anvil.addRecipe(<mwc:arprsprecisionstock>, [<hbm:wire_aluminium>, <hbm:plate_aluminium>*2], 3);
mods.ntm.Anvil.addRecipe(<mwc:collapsablemoestockgreen>, [<hbm:wire_aluminium>, <hbm:plate_aluminium>*2], 3);
mods.ntm.Anvil.addRecipe(<mwc:collapsablemoestock>, [<hbm:wire_aluminium>, <hbm:plate_aluminium>*2], 3);
mods.ntm.Anvil.addRecipe(<mwc:vssvintorezstock>, [<hbm:wire_aluminium>, <hbm:plate_aluminium>*2], 3);
mods.ntm.Anvil.addRecipe(<mwc:hk416stock>, [<hbm:wire_aluminium>, <hbm:plate_aluminium>*2], 3);
mods.ntm.Anvil.addRecipe(<mwc:hk416stocktan>, [<hbm:wire_aluminium>, <hbm:plate_aluminium>*2], 3);
mods.ntm.Anvil.addRecipe(<mwc:m110stock>, [<hbm:wire_aluminium>, <hbm:plate_aluminium>*2], 3);
mods.ntm.Anvil.addRecipe(<mwc:fnfalstock>, [<hbm:wire_aluminium>, <hbm:plate_aluminium>*2], 3);
mods.ntm.Anvil.addRecipe(<mwc:remington870stock>, [<hbm:wire_aluminium>, <hbm:plate_aluminium>*2], 3);
mods.ntm.Anvil.addRecipe(<mwc:remington870policemagnumstock>, [<hbm:wire_aluminium>, <hbm:plate_aluminium>*2], 3);
mods.ntm.Anvil.addRecipe(<mwc:kedrstock>, [<hbm:wire_aluminium>, <hbm:plate_aluminium>*2], 3);
mods.ntm.Anvil.addRecipe(<mwc:cz805brenstock>, [<hbm:wire_aluminium>, <hbm:plate_aluminium>*2], 3);
mods.ntm.Anvil.addRecipe(<mwc:milspecstock>, [<hbm:wire_aluminium>, <hbm:plate_aluminium>*2], 3);
mods.ntm.Anvil.addRecipe(<mwc:magpulctrstocktan>, [<hbm:wire_aluminium>, <hbm:plate_aluminium>*2], 3);
mods.ntm.Anvil.addRecipe(<mwc:magpulctrstock>, [<hbm:wire_aluminium>, <hbm:plate_aluminium>*2], 3);
mods.ntm.Anvil.addRecipe(<mwc:remington870sawedgrip>, [<hbm:wire_aluminium>, <hbm:plate_aluminium>*2], 3);
//KITs
mods.ntm.Anvil.addRecipe(<mwc:p90swordfish>, <hbm:ingot_aluminium>, 3);
mods.ntm.Anvil.addRecipe(<mwc:p90defaultkit>, <hbm:ingot_aluminium>, 3);
mods.ntm.Anvil.addRecipe(<mwc:p90terminator>, <hbm:ingot_aluminium>, 3);
mods.ntm.Anvil.addRecipe(<mwc:auga1>, <hbm:ingot_aluminium>, 3);
mods.ntm.Anvil.addRecipe(<mwc:augdefaultkit>, <hbm:ingot_aluminium>, 3);
mods.ntm.Anvil.addRecipe(<mwc:augparaconversion>, <hbm:ingot_aluminium>, 3);
//BODYs
mods.ntm.Anvil.addRecipe(<mwc:m1911body>, [<hbm:wire_aluminium>, <hbm:plate_steel>*2, <hbm:ingot_steel>], 3);
mods.ntm.Anvil.addRecipe(<mwc:m191144magbody>, [<hbm:wire_aluminium>, <hbm:plate_steel>*2, <hbm:ingot_steel>], 3);
mods.ntm.Anvil.addRecipe(<mwc:m9a1body>, [<hbm:wire_aluminium>, <hbm:plate_steel>*2, <hbm:ingot_steel>], 3);
mods.ntm.Anvil.addRecipe(<mwc:deserteaglebody>, [<hbm:wire_aluminium>, <hbm:plate_steel>*2, <hbm:ingot_steel>], 3);
mods.ntm.Anvil.addRecipe(<mwc:deserteaglelongbody>, [<hbm:wire_aluminium>, <hbm:plate_steel>*2, <hbm:ingot_steel>], 3);
mods.ntm.Anvil.addRecipe(<mwc:deserteaglebodygolden>, [<hbm:wire_aluminium>, <hbm:plate_steel>*2, <hbm:ingot_steel>], 3);
mods.ntm.Anvil.addRecipe(<mwc:deserteaglebodyblack>, [<hbm:wire_aluminium>, <hbm:plate_steel>*2, <hbm:ingot_steel>], 3);
mods.ntm.Anvil.addRecipe(<mwc:glock19body>, [<hbm:wire_aluminium>, <hbm:plate_steel>*2, <hbm:ingot_steel>], 3);
mods.ntm.Anvil.addRecipe(<mwc:glock19xbody>, [<hbm:wire_aluminium>, <hbm:plate_steel>*2, <hbm:ingot_steel>], 3);
mods.ntm.Anvil.addRecipe(<mwc:mac10body>, [<hbm:wire_aluminium>, <hbm:plate_steel>*2, <hbm:ingot_steel>], 3);
mods.ntm.Anvil.addRecipe(<mwc:samuraiedgebody>, [<hbm:wire_aluminium>, <hbm:plate_steel>*2, <hbm:ingot_steel>], 3);
mods.ntm.Anvil.addRecipe(<mwc:makarovpbbody>, [<hbm:wire_aluminium>, <hbm:plate_steel>*2, <hbm:ingot_steel>], 3);
mods.ntm.Anvil.addRecipe(<mwc:makarovbody>, [<hbm:wire_aluminium>, <hbm:plate_steel>*2, <hbm:ingot_steel>], 3);
mods.ntm.Anvil.addRecipe(<mwc:sccycpx2bodytan>, [<hbm:wire_aluminium>, <hbm:plate_steel>*2, <hbm:ingot_steel>], 3);
mods.ntm.Anvil.addRecipe(<mwc:sccycpx2body>, [<hbm:wire_aluminium>, <hbm:plate_steel>*2, <hbm:ingot_steel>], 3);
mods.ntm.Anvil.addRecipe(<mwc:glockrazorbackbody>, [<hbm:wire_aluminium>, <hbm:plate_steel>*2, <hbm:ingot_steel>], 3);
mods.ntm.Anvil.addRecipe(<mwc:krissvector556handguard>, [<hbm:wire_aluminium>, <hbm:plate_steel>*2, <hbm:ingot_steel>], 3);
mods.ntm.Anvil.addRecipe(<mwc:m1carbinebody>, [<hbm:wire_aluminium>, <hbm:plate_steel>*2, <hbm:ingot_steel>], 3);
mods.ntm.Anvil.addRecipe(<mwc:m1a1carbinebody>, [<hbm:wire_aluminium>, <hbm:plate_steel>*2, <hbm:ingot_steel>], 3);
//SLIDEs
mods.ntm.Anvil.addRecipe(<mwc:glock19slide>, <hbm:plate_steel>*2, 3);
mods.ntm.Anvil.addRecipe(<mwc:glock18cslide>, <hbm:plate_steel>*2, 3);
mods.ntm.Anvil.addRecipe(<mwc:glock18ccncslide>, <hbm:plate_steel>*2, 3);
mods.ntm.Anvil.addRecipe(<mwc:glock19xslide>, <hbm:plate_steel>*2, 3);
mods.ntm.Anvil.addRecipe(<mwc:glockrazorbackslide>, <hbm:plate_steel>*2, 3);
mods.ntm.Anvil.addRecipe(<mwc:mp443slide>, <hbm:plate_steel>*2, 3);
mods.ntm.Anvil.addRecipe(<mwc:makarovpbslide>, <hbm:plate_steel>*2, 3);
mods.ntm.Anvil.addRecipe(<mwc:makarovpmslide>, <hbm:plate_steel>*2, 3);
mods.ntm.Anvil.addRecipe(<mwc:fivesevenslide>, <hbm:plate_steel>*2, 3);
mods.ntm.Anvil.addRecipe(<mwc:makarov_slide>, <hbm:plate_steel>*2, 3);
mods.ntm.Anvil.addRecipe(<mwc:p226slide>, <hbm:plate_steel>*2, 3);
mods.ntm.Anvil.addRecipe(<mwc:m1911slide>, <hbm:plate_steel>*2, 3);
mods.ntm.Anvil.addRecipe(<mwc:browninghipowerslide>, <hbm:plate_steel>*2, 3);
mods.ntm.Anvil.addRecipe(<mwc:albert01r_slide>, <hbm:plate_steel>*2, 3);
mods.ntm.Anvil.addRecipe(<mwc:m9a1slide>, <hbm:plate_steel>*2, 3);
mods.ntm.Anvil.addRecipe(<mwc:p12_slide>, <hbm:plate_steel>*2, 3);
mods.ntm.Anvil.addRecipe(<mwc:sccycpx2slide>, <hbm:plate_steel>*2, 3);
mods.ntm.Anvil.addRecipe(<mwc:deserteagleslidegolden>, <hbm:plate_steel>*2, 3);
mods.ntm.Anvil.addRecipe(<mwc:mas21slide>, <hbm:plate_steel>*2, 3);
mods.ntm.Anvil.addRecipe(<mwc:m17_slide>, <hbm:plate_steel>*2, 3);
mods.ntm.Anvil.addRecipe(<mwc:m45a1slide>, <hbm:plate_steel>*2, 3);
mods.ntm.Anvil.addRecipe(<mwc:apsslide>, <hbm:plate_steel>*2, 3);
mods.ntm.Anvil.addRecipe(<mwc:vp70slide>, <hbm:plate_steel>*2, 3);
mods.ntm.Anvil.addRecipe(<mwc:deserteagleslideblack>, <hbm:plate_steel>*2, 3);
mods.ntm.Anvil.addRecipe(<mwc:deserteagleslide>, <hbm:plate_steel>*2, 3);
mods.ntm.Anvil.addRecipe(<mwc:glock19rockslideolive>, <hbm:plate_steel>*2, 3);
mods.ntm.Anvil.addRecipe(<mwc:glock19ghostprecisionslide>, <hbm:plate_steel>*2, 3);
mods.ntm.Anvil.addRecipe(<mwc:sccycpx2bslide>, <hbm:plate_steel>*2, 3);
mods.ntm.Anvil.addRecipe(<mwc:m191144magslide>, <hbm:plate_steel>*2, 3);
mods.ntm.Anvil.addRecipe(<mwc:samuraiedgeslide>, <hbm:plate_steel>*2, 3);
//RAILs
mods.ntm.Anvil.addRecipe(<mwc:kar98krail>, <hbm:plate_aluminium>, 3);
mods.ntm.Anvil.addRecipe(<mwc:m60rail>, <hbm:plate_aluminium>, 3);
mods.ntm.Anvil.addRecipe(<mwc:m16a1picatinnyrail>, <hbm:plate_aluminium>, 3);
mods.ntm.Anvil.addRecipe(<mwc:famasf1picatinnyrail>, <hbm:plate_aluminium>, 3);
mods.ntm.Anvil.addRecipe(<mwc:railriser>, <hbm:plate_aluminium>, 3);
mods.ntm.Anvil.addRecipe(<mwc:acrrails>, <hbm:plate_aluminium>, 3);
mods.ntm.Anvil.addRecipe(<mwc:m14dmrrail>, <hbm:plate_aluminium>, 3);
mods.ntm.Anvil.addRecipe(<mwc:m4rail>, <hbm:plate_aluminium>, 3);
mods.ntm.Anvil.addRecipe(<mwc:ngswrrail>, <hbm:plate_aluminium>, 3);
mods.ntm.Anvil.addRecipe(<mwc:m110rail>, <hbm:plate_aluminium>, 3);
mods.ntm.Anvil.addRecipe(<mwc:aacrail>, <hbm:plate_aluminium>, 3);
mods.ntm.Anvil.addRecipe(<mwc:railalt>, <hbm:plate_aluminium>, 3);
mods.ntm.Anvil.addRecipe(<mwc:magnumrail>, <hbm:plate_aluminium>, 3);
mods.ntm.Anvil.addRecipe(<mwc:m4asiimovrail>, <hbm:plate_aluminium>, 3);
mods.ntm.Anvil.addRecipe(<mwc:mimp5trrail>, <hbm:plate_aluminium>, 3);
mods.ntm.Anvil.addRecipe(<mwc:mimp5mrail>, <hbm:plate_aluminium>, 3);
mods.ntm.Anvil.addRecipe(<mwc:shotgunrail>, <hbm:plate_aluminium>, 3);
//CHASSISes
mods.ntm.Assembler.addRecipe(<mwc:remington700mdtxrschassis>, [<hbm:plate_steel>*2, <hbm:ingot_steel>*3, <hbm:wire_aluminium>], 30);
mods.ntm.Assembler.addRecipe(<mwc:remington700chassis>, [<hbm:plate_steel>*2, <hbm:ingot_steel>*3, <hbm:wire_aluminium>], 30);
mods.ntm.Assembler.addRecipe(<mwc:ssg08chassis>, [<hbm:plate_steel>*2, <hbm:ingot_steel>*3, <hbm:wire_aluminium>], 30);
mods.ntm.Assembler.addRecipe(<mwc:arx160chassis>, [<hbm:plate_steel>*2, <hbm:ingot_steel>*3, <hbm:wire_aluminium>], 30);
mods.ntm.Assembler.addRecipe(<mwc:m14body>, [<hbm:plate_steel>*2, <hbm:ingot_steel>*3, <hbm:wire_aluminium>], 30);
mods.ntm.Assembler.addRecipe(<mwc:m14dmrsocomchassis>, [<hbm:plate_steel>*2, <hbm:ingot_steel>*3, <hbm:wire_aluminium>], 30);
mods.ntm.Assembler.addRecipe(<mwc:mk14tanbody>, [<hbm:plate_steel>*2, <hbm:ingot_steel>*3, <hbm:wire_aluminium>], 30);
mods.ntm.Assembler.addRecipe(<mwc:mk14snowbody>, [<hbm:plate_steel>*2, <hbm:ingot_steel>*3, <hbm:wire_aluminium>], 30);
mods.ntm.Assembler.addRecipe(<mwc:mk14blackbody>, [<hbm:plate_steel>*2, <hbm:ingot_steel>*3, <hbm:wire_aluminium>], 30);
mods.ntm.Assembler.addRecipe(<mwc:remington700apacchassis>, [<hbm:plate_steel>*2, <hbm:ingot_steel>*3, <hbm:wire_aluminium>], 30);
//COVERs
mods.ntm.Anvil.addRecipe(<mwc:dragunovdustcover>, <hbm:plate_steel>*2, 3);
mods.ntm.Anvil.addRecipe(<mwc:dragunov98dustcover>, <hbm:plate_steel>*2, 3);
mods.ntm.Anvil.addRecipe(<mwc:akmdustcover>, <hbm:plate_steel>*2, 3);
mods.ntm.Anvil.addRecipe(<mwc:ak101dustcover>, <hbm:plate_steel>*2, 3);
mods.ntm.Anvil.addRecipe(<mwc:ak15dustcover>, <hbm:plate_steel>*2, 3);
mods.ntm.Anvil.addRecipe(<mwc:ak15dustcover>, <hbm:plate_steel>*2, 3);
mods.ntm.Anvil.addRecipe(<mwc:ak12dustcover>, <hbm:plate_steel>*2, 3);
mods.ntm.Anvil.addRecipe(<mwc:ak12bdustcover>, <hbm:plate_steel>*2, 3);
mods.ntm.Anvil.addRecipe(<mwc:vssvintorezdustcover>, <hbm:plate_steel>*2, 3);
mods.ntm.Anvil.addRecipe(<mwc:sa58dustcover>, <hbm:plate_steel>*2, 3);
mods.ntm.Anvil.addRecipe(<mwc:veprdustcover>, <hbm:plate_steel>*2, 3);
mods.ntm.Anvil.addRecipe(<mwc:fnfaldustcover>, <hbm:plate_steel>*2, 3);
mods.ntm.Anvil.addRecipe(<mwc:vssmdustcover>, <hbm:plate_steel>*2, 3);
mods.ntm.Anvil.addRecipe(<mwc:m14cover>, <hbm:plate_steel>*2, 3);
mods.ntm.Anvil.addRecipe(<mwc:m14trirailcover>, <hbm:plate_steel>*2, 3);
mods.ntm.Anvil.addRecipe(<mwc:ak47dustcover>, <hbm:plate_steel>*2, 3);
//PUMPs
mods.ntm.Anvil.addRecipe(<mwc:m1897pump>, <hbm:plate_steel>, 3);
mods.ntm.Anvil.addRecipe(<mwc:remington870fabdefensepump>, <hbm:plate_steel>, 3);
mods.ntm.Anvil.addRecipe(<mwc:remington870policemagnumpump>, <hbm:plate_steel>, 3);
mods.ntm.Anvil.addRecipe(<mwc:remington870magpulpump>, <hbm:plate_steel>, 3);
mods.ntm.Anvil.addRecipe(<mwc:remington870pump>, <hbm:plate_steel>, 3);
mods.ntm.Anvil.addRecipe(<mwc:super90pump>, <hbm:plate_steel>, 3);
mods.ntm.Anvil.addRecipe(<mwc:m500a2pump>, <hbm:plate_steel>, 3);
mods.ntm.Anvil.addRecipe(<mwc:hescspump>, <hbm:plate_steel>, 3);
mods.ntm.Anvil.addRecipe(<mwc:ks23pump>, <hbm:plate_steel>, 3);
mods.ntm.Anvil.addRecipe(<mwc:supernovapump>, <hbm:plate_steel>, 3);
