import mods.ntm.Anvil; 

mods.ntm.Anvil.addRecipe(<opencomputers:upgrade:1>, [<hbm:upgrade_template>, <hbm:battery_generic>], 4);
mods.ntm.Anvil.addRecipe(<opencomputers:upgrade:2>, [<hbm:upgrade_template>, <hbm:battery_advanced>], 4);
mods.ntm.Anvil.addRecipe(<opencomputers:upgrade:3>, [<hbm:upgrade_template>, <hbm:battery_lithium>], 4);
mods.ntm.Anvil.addRecipe(<aeadditions:oc.upgrade:2>, [<hbm:upgrade_template>, <appliedenergistics2:material:41>, <hbm:circuit_aluminium>, <hbm:coil_copper>], 4);
mods.ntm.Anvil.addRecipe(<aeadditions:oc.upgrade:1>, [<hbm:upgrade_template>, <appliedenergistics2:material:41>, <hbm:circuit_copper>, <hbm:coil_copper>*2], 4);
mods.ntm.Anvil.addRecipe(<aeadditions:oc.upgrade>, [<hbm:upgrade_template>, <appliedenergistics2:material:41>, <hbm:circuit_raw>, <hbm:coil_copper>*3], 4);
mods.ntm.Anvil.addRecipe(<opencomputers:upgrade:5>, [<hbm:upgrade_template>, <ironchest:iron_chest>, <ore:oc:circuitChip1>], 4);
mods.ntm.Anvil.addRecipe(<opencomputers:upgrade:6>, [<hbm:upgrade_template>, <ironchest:iron_chest:1>, <ore:oc:circuitChip2>], 4);
mods.ntm.Anvil.addRecipe(<opencomputers:upgrade:7>, [<hbm:upgrade_template>, <ironchest:iron_chest:2>, <ore:oc:circuitChip3>], 4);
mods.ntm.Anvil.addRecipe(<opencomputers:upgrade:8>, [<hbm:upgrade_template>, <ironchest:iron_chest:3>], 4);
mods.ntm.Anvil.addRecipe(<opencomputers:upgrade:9>, [<hbm:upgrade_template>, <ironchest:iron_chest:5>], 4);
mods.ntm.Anvil.addRecipe(<opencomputers:upgrade:10>, [<hbm:upgrade_template>, <ironchest:iron_chest:6>], 4);
mods.ntm.Anvil.addRecipe(<opencomputers:upgrade:12>, [<hbm:upgrade_template>, <opencomputers:card:10>], 4);
mods.ntm.Anvil.addRecipe(<opencomputers:upgrade:13>, [<hbm:upgrade_template>, <opencomputers:card:11>], 4);
mods.ntm.Anvil.addRecipe(<opencomputers:upgrade:14>, [<hbm:upgrade_template>, <opencomputers:card:12>], 4);
mods.ntm.Anvil.addRecipe(<opencomputers:upgrade:27>, [<hbm:upgrade_template>, <hbm:jetpack_fly>], 4);
mods.ntm.Anvil.addRecipe(<opencomputers:upgrade:28>, [<hbm:upgrade_template>, <hbm:jetpack_break>], 4);
mods.ntm.Anvil.addRecipe(<opencomputers:upgrade:17>, [<hbm:upgrade_template>, <ironchest:wood_iron_chest_upgrade>], 4);
mods.ntm.Anvil.addRecipe(<opencomputers:upgrade:18>, [<hbm:upgrade_template>, <ironchest:wood_copper_chest_upgrade>], 4);
mods.ntm.Anvil.addRecipe(<opencomputers:upgrade:23>, [<hbm:upgrade_template>, <minecraft:bucket>], 4);
mods.ntm.Anvil.addRecipe(<opencomputers:upgrade:24>, [<hbm:upgrade_template>, <minecraft:bucket>, <ore:oc:circuitChip3>], 4);
mods.ntm.Anvil.addRecipe(<opencomputers:upgrade:11>, [<hbm:upgrade_template>, <minecraft:crafting_table>], 4);
mods.ntm.Anvil.addRecipe(<opencomputers:upgrade:4>, [<hbm:upgrade_template>, <warpdrive:chunk_loader.basic>], 4);
mods.ntm.Anvil.addRecipe(<opencomputers:upgrade>, [<hbm:upgrade_template>, <hbm:motor_desh>], 4);
mods.ntm.Anvil.addRecipe(<opencomputers:upgrade:15>, [<hbm:upgrade_template>, <hbm:tank_steel>, <minecraft:experience_bottle>], 4);
mods.ntm.Anvil.addRecipe(<opencomputers:upgrade:16>, [<hbm:upgrade_template>, <hbm:machine_coal_off>], 4);
mods.ntm.Anvil.addRecipe(<opencomputers:upgrade:26>, [<hbm:upgrade_template>, <minecraft:lead>], 4);
mods.ntm.Anvil.addRecipe(<opencomputers:upgrade:30>, [<hbm:upgrade_template>, <hbm:reacher>], 4);
mods.ntm.Anvil.addRecipe(<opencomputers:upgrade:19>, [<hbm:upgrade_template>, <minecraft:map>, <minecraft:compass>], 4);
mods.ntm.Anvil.addRecipe(<opencomputers:upgrade:20>, [<hbm:upgrade_template>, <minecraft:piston>], 4);
mods.ntm.Anvil.addRecipe(<opencomputers:upgrade:33>, [<hbm:upgrade_template>, <minecraft:sticky_piston>], 4);
mods.ntm.Anvil.addRecipe(<opencomputers:upgrade:21>, [<hbm:upgrade_template>, <ore:dye>, <minecraft:feather>], 4);
mods.ntm.Anvil.addRecipe(<opencomputers:upgrade:22>, [<hbm:upgrade_template>, <hbm:solar_mirror>, <hbm:machine_solar_boiler>], 4);
mods.ntm.Anvil.addRecipe(<opencomputers:upgrade:25>, [<hbm:upgrade_template>, <hbm:horseshoe_magnet>], 4);
mods.ntm.Anvil.addRecipe(<opencomputers:upgrade:29>, [<hbm:upgrade_template>, <minecraft:emerald>*64], 4);
