import mods.recipestages.Recipes;

mods.recipestages.Recipes.addShaped("never", <computronics:audio_cable>,[[null, null, null],[<minecraft:iron_ingot>, <minecraft:noteblock>, <minecraft:iron_ingot>],[null, null, null]]);
mods.recipestages.Recipes.addShaped("never", <computronics:oc_parts:1>,[[<minecraft:iron_ingot>, <opencomputers:material:6>, <minecraft:iron_ingot>],[<opencomputers:material:8>, <computronics:chat_box>, <opencomputers:material:8>],[<minecraft:iron_ingot>, <opencomputers:material:4>, <minecraft:iron_ingot>]]);
mods.recipestages.Recipes.addShaped("never", <computronics:oc_parts:4>,[[],[],[]]);
mods.recipestages.Recipes.addShaped("never", <computronics:oc_parts:11>,[[],[],[]]);
mods.recipestages.Recipes.addShaped("never", <computronics:iron_note_block>,[[],[],[]]);
mods.recipestages.Recipes.addShaped("never", <computronics:cipher_advanced>,[[],[],[]]);
mods.recipestages.Recipes.addShaped("never", <computronics:tape:5>,[[],[],[]]);
mods.recipestages.Recipes.addShaped("never", <computronics:oc_parts:10>,[[],[],[]]);
mods.recipestages.Recipes.addShaped("never", <computronics:tape_reader>,[[],[],[]]);
mods.recipestages.Recipes.addShaped("never", <computronics:camera>,[[],[],[]]);
mods.recipestages.Recipes.addShaped("never", <computronics:chat_box>,[[],[],[]]);
mods.recipestages.Recipes.addShaped("never", <computronics:cipher>,[[],[],[]]);
mods.recipestages.Recipes.addShaped("never", <computronics:tape>,[[],[],[]]);
mods.recipestages.Recipes.addShaped("never", <computronics:tape:1>,[[],[],[]]);
mods.recipestages.Recipes.addShaped("never", <computronics:tape:3>,[[],[],[]]);
mods.recipestages.Recipes.addShaped("never", <computronics:tape:4>,[[],[],[]]);
mods.recipestages.Recipes.addShaped("never", <computronics:tape:6>,[[],[],[]]);
mods.recipestages.Recipes.addShaped("never", <computronics:tape:8>,[[],[],[]]);
mods.recipestages.Recipes.addShaped("never", <computronics:portable_tape_drive>,[[],[],[]]);
mods.recipestages.Recipes.addShaped("never", <computronics:oc_parts:3>,[[],[],[]]);
mods.recipestages.Recipes.addShaped("never", <computronics:oc_parts:5>,[[],[],[]]);
mods.recipestages.Recipes.addShaped("never", <computronics:oc_parts:6>,[[],[],[]]);
mods.recipestages.Recipes.addShaped("never", <computronics:oc_parts:12>,[[],[],[]]);
mods.recipestages.Recipes.addShaped("never", <computronics:oc_parts:13>,[[],[],[]]);
mods.recipestages.Recipes.addShaped("never", <computronics:speaker>,[[],[],[]]);
mods.recipestages.Recipes.addShaped("never", <computronics:colorful_lamp>,[[],[],[]]);
mods.recipestages.Recipes.addShaped("never", <computronics:parts>,[[],[],[]]);
mods.recipestages.Recipes.addShaped("never", <computronics:oc_parts>,[[],[],[]]);
mods.recipestages.Recipes.addShaped("never", <computronics:oc_parts:2>,[[],[],[]]);
mods.recipestages.Recipes.addShaped("never", <computronics:oc_parts:7>.withTag({"oc:data": {}}),[[],[],[]]);
mods.recipestages.Recipes.addShaped("never", <computronics:oc_parts:8>,[[],[],[]]);
mods.recipestages.Recipes.addShaped("never", <computronics:oc_parts:9>,[[],[],[]]);
mods.recipestages.Recipes.addShaped("never", <computronics:oc_parts:14>,[[],[],[]]);
mods.recipestages.Recipes.addShaped("never", <computronics:radar>,[[],[],[]]);
mods.recipestages.Recipes.addShaped("never", <computronics:tape:2>,[[],[],[]]);
mods.recipestages.Recipes.addShaped("never", <computronics:speech_box>,[[],[],[]]);
