import mods.ntm.Anvil;

mods.ntm.Anvil.addRecipe(<hbm:dns_helmet>.withTag({charge: 1000000000 as long, theoneprobe: 1, display: {Name: "DNT Nano Suit Helmet with Probe"}}), [<hbm:dns_helmet>, <theoneprobe:probe>], 1);
mods.ntm.Anvil.addRecipe(<hbm:cmb_helmet>.withTag({theoneprobe: 1, display: {Name: "CMD Steel Helmet with Probe"}}), [<hbm:cmb_helmet>, <theoneprobe:probe>], 1);
mods.ntm.Anvil.addRecipe(<hbm:schrabidium_helmet>.withTag({theoneprobe: 1, display: {Name: "Schrabidium Helmet with Probe"}}), [<hbm:schrabidium_helmet>, <theoneprobe:probe>], 1);
mods.ntm.Anvil.addRecipe(<hbm:t45_helmet>.withTag({charge: 1000000 as long, theoneprobe: 1, display: {Name: "T-45 Power Armor Helmet with Probe"}}), [<hbm:t45_helmet>, <theoneprobe:probe>], 1);
mods.ntm.Anvil.addRecipe(<hbm:ajr_helmet>.withTag({charge: 2500000 as long, theoneprobe: 1, display: {Name: "T-60 Ranger Power Armor Helmet with Probe"}}), [<hbm:ajr_helmet>, <theoneprobe:probe>], 1);
mods.ntm.Anvil.addRecipe(<hbm:ajro_helmet>.withTag({charge: 2500000 as long, theoneprobe: 1, display: {Name: "T-60 AJR Power Armor Helmet with Probe"}}), [<hbm:ajro_helmet>, <theoneprobe:probe>], 1);
mods.ntm.Anvil.addRecipe(<hbm:hev_helmet>.withTag({charge: 5000000 as long, theoneprobe: 1, display: {Name: "HEV Mark IV Helmet with Probe"}}), [<hbm:hev_helmet>, <theoneprobe:probe>], 1);
mods.ntm.Anvil.addRecipe(<hbm:bj_helmet>.withTag({charge: 10000000 as long, theoneprobe: 1, display: {Name: "Eyepatch with Thermal Sensor and Probe"}}), [<hbm:bj_helmet>, <theoneprobe:probe>], 1);
mods.ntm.Anvil.addRecipe(<hbm:rpa_helmet>.withTag({charge: 50000000 as long, theoneprobe: 1, display: {Name: "X-01 Remnants Power Armor Helmet with Probe"}}), [<hbm:rpa_helmet>, <theoneprobe:probe>], 1);
mods.ntm.Anvil.addRecipe(<hbm:fau_helmet>.withTag({charge: 100000000 as long, theoneprobe: 1, display: {Name: "Fau Helmet with Probe"}}), [<hbm:fau_helmet>, <theoneprobe:probe>], 1);
mods.ntm.Anvil.addRecipe(<hbm:hazmat_helmet>.withTag({theoneprobe: 1, display: {Name: "Hazmat Helmet with Probe"}}), [<hbm:hazmat_helmet>, <theoneprobe:probe>], 1);
mods.ntm.Anvil.addRecipe(<hbm:hazmat_helmet_red>.withTag({theoneprobe: 1, display: {Name: "Advanced Hazmat Helmet with Probe"}}), [<hbm:hazmat_helmet_red>, <theoneprobe:probe>], 1);
mods.ntm.Anvil.addRecipe(<hbm:hazmat_helmet_grey>.withTag({theoneprobe: 1, display: {Name: "High-Perfomance Hazmat Helmet with Probe"}}), [<hbm:hazmat_helmet_grey>, <theoneprobe:probe>], 1);
mods.ntm.Anvil.addRecipe(<hbm:liquidator_helmet>.withTag({theoneprobe: 1, display: {Name: "Liquidator Suit Helmet with Probe"}}), [<hbm:liquidator_helmet>, <theoneprobe:probe>], 1);
mods.ntm.Anvil.addRecipe(<hbm:hazmat_paa_helmet>.withTag({theoneprobe: 1, display: {Name: "PaA Hazmat Helmet with Probe"}}), [<hbm:hazmat_paa_helmet>, <theoneprobe:probe>], 1);
mods.ntm.Anvil.addRecipe(<hbm:paa_helmet>.withTag({theoneprobe: 1, display: {Name: "PaA Helmet Protection with Probe"}}), [<hbm:paa_helmet>, <theoneprobe:probe>], 1);
mods.ntm.Anvil.addRecipe(<hbm:asbestos_helmet>.withTag({theoneprobe: 1, display: {Name: "Fire Proximity Helmet with Probe"}}), [<hbm:asbestos_helmet>, <theoneprobe:probe>], 1);
mods.ntm.Anvil.addRecipe(<hbm:steel_helmet>.withTag({theoneprobe: 1, display: {Name: "Steel Helmet with Probe"}}), [<hbm:steel_helmet>, <theoneprobe:probe>], 1);
mods.ntm.Anvil.addRecipe(<hbm:titanium_helmet>.withTag({theoneprobe: 1, display: {Name: "Titanium Helmet with Probe"}}), [<hbm:titanium_helmet>, <theoneprobe:probe>], 1);
mods.ntm.Anvil.addRecipe(<hbm:alloy_helmet>.withTag({theoneprobe: 1, display: {Name: "Advanced Alloy Helmet with Probe"}}), [<hbm:alloy_helmet>, <theoneprobe:probe>], 1);
mods.ntm.Anvil.addRecipe(<hbm:cobalt_helmet>.withTag({theoneprobe: 1, display: {Name: "Cobalt Helmet with Probe"}}), [<hbm:cobalt_helmet>, <theoneprobe:probe>], 1);
mods.ntm.Anvil.addRecipe(<hbm:security_helmet>.withTag({theoneprobe: 1, display: {Name: "Security Helmet with Probe"}}), [<hbm:security_helmet>, <theoneprobe:probe>], 1);
mods.ntm.Anvil.addRecipe(<hbm:starmetal_helmet>.withTag({theoneprobe: 1, display: {Name: "Starmetal Helmet with Probe"}}), [<hbm:starmetal_helmet>, <theoneprobe:probe>], 1);
